#!/usr/bin/env node
/**
 * VAD-on-WAV example harness.
 *
 * Feeds a real WAV file (typically generated by the local Eliza-1 TTS path)
 * through the plugin-local-inference VAD implementation and records the emitted events.
 * This is intentionally separate from `vad_quality_harness.mjs`: the quality
 * harness uses labelled synthetic fixtures for gates; this file proves the
 * detector path on concrete generated voice artifacts.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PLUGIN_ROOT = path.resolve(__dirname, "..", "..");
const REPO_ROOT = path.resolve(PLUGIN_ROOT, "..", "..");
const DEFAULT_BUNDLE = path.join(
  os.homedir(),
  ".eliza",
  "local-inference",
  "models",
  "eliza-1-0_8b.bundle",
);
const DEFAULT_WAV = "/tmp/omnivoice-metal-fused-codec-cpu-fallback.wav";
const DEFAULT_REPORT = path.join(
  PLUGIN_ROOT,
  "native",
  "verify",
  "reports",
  `vad-from-wav-${timestamp()}.json`,
);

function timestamp() {
  return new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "Z");
}

function parseArgs(argv) {
  const args = {
    bundle: DEFAULT_BUNDLE,
    wav: DEFAULT_WAV,
    report: DEFAULT_REPORT,
    lib: process.env.ELIZA_SILERO_VAD_LIB || null,
    json: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--bundle") args.bundle = argv[++i] ?? args.bundle;
    else if (a === "--wav") args.wav = argv[++i] ?? args.wav;
    else if (a === "--report") args.report = argv[++i] ?? args.report;
    else if (a === "--lib" || a === "--dylib")
      args.lib = argv[++i] ?? args.lib;
    else if (a === "--json") args.json = true;
    else if (a === "--help" || a === "-h") {
      console.log(
        "Usage: node vad_from_wav_example.mjs [--bundle PATH] [--wav PATH] [--report PATH] [--lib PATH] [--json]",
      );
      process.exit(0);
    }
  }
  args.bundle = path.resolve(args.bundle);
  args.wav = path.resolve(args.wav);
  args.report = path.resolve(args.report);
  if (args.lib) args.lib = path.resolve(args.lib);
  return args;
}

function bunRunner() {
  for (const cmd of [
    "bun",
    path.join(os.homedir(), ".bun", "bin", "bun"),
    "/opt/homebrew/bin/bun",
    "/usr/local/bin/bun",
  ]) {
    const probe = spawnSync(cmd, ["--version"], { encoding: "utf8" });
    if (probe.status === 0) return { cmd, args: [] };
  }
  return null;
}

function typescriptRunner(preferBun = false) {
  if (preferBun) {
    const runtime = bunRunner();
    if (runtime) return runtime;
  }
  if (fs.existsSync(path.join(REPO_ROOT, "node_modules", ".bin", "tsx"))) {
    for (const cmd of [
      "/opt/homebrew/bin/node",
      "/usr/local/bin/node",
      process.execPath,
    ]) {
      if (cmd && fs.existsSync(cmd)) {
        return { cmd, args: ["--import", "tsx"] };
      }
    }
  }
  if (!preferBun) {
    const runtime = bunRunner();
    if (runtime) return runtime;
  }
  if (fs.existsSync(path.join(REPO_ROOT, "node_modules", ".bin", "tsx"))) {
    return { cmd: process.execPath, args: ["--import", "tsx"] };
  }
  return null;
}

function makeRunnerSource(args) {
  const vadUrl = pathToFileURL(
    path.join(
      PLUGIN_ROOT,
      "src",
      "services",
      "voice",
      "vad.ts",
    ),
  ).href;

  return `
import fs from "node:fs";
import { performance } from "node:perf_hooks";
import { createSileroVadDetector, resolveSileroVadCppGgufPath } from ${JSON.stringify(vadUrl)};

const bundleRoot = ${JSON.stringify(args.bundle)};
const wavPath = ${JSON.stringify(args.wav)};
const libraryPath = ${JSON.stringify(args.lib)};
const SR = 16000;
const FRAME = 512;

function readWavPcm16Mono(file) {
  const buf = fs.readFileSync(file);
  if (buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WAVE") {
    throw new Error("unsupported WAV container");
  }
  let offset = 12;
  let audioFormat = 0;
  let channels = 0;
  let sampleRateHz = 0;
  let bitsPerSample = 0;
  let dataOffset = -1;
  let dataBytes = 0;
  while (offset + 8 <= buf.length) {
    const id = buf.toString("ascii", offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    offset += 8;
    if (id === "fmt ") {
      audioFormat = buf.readUInt16LE(offset);
      channels = buf.readUInt16LE(offset + 2);
      sampleRateHz = buf.readUInt32LE(offset + 4);
      bitsPerSample = buf.readUInt16LE(offset + 14);
    } else if (id === "data") {
      dataOffset = offset;
      dataBytes = size;
      break;
    }
    offset += size + (size & 1);
  }
  if (audioFormat !== 1 || channels !== 1 || bitsPerSample !== 16 || dataOffset < 0) {
    throw new Error(\`expected mono PCM16 WAV; got format=\${audioFormat} channels=\${channels} bits=\${bitsPerSample}\`);
  }
  const samples = Math.floor(dataBytes / 2);
  const pcm = new Float32Array(samples);
  for (let i = 0; i < samples; i += 1) {
    pcm[i] = Math.max(-1, buf.readInt16LE(dataOffset + i * 2) / 32768);
  }
  return { pcm, sampleRateHz, samples, dataBytes };
}

function resampleLinear(pcm, fromRate, toRate) {
  if (fromRate === toRate) return pcm;
  const ratio = toRate / fromRate;
  const outLen = Math.max(1, Math.round(pcm.length * ratio));
  const out = new Float32Array(outLen);
  for (let i = 0; i < outLen; i += 1) {
    const pos = i / ratio;
    const i0 = Math.floor(pos);
    const i1 = Math.min(i0 + 1, pcm.length - 1);
    const frac = pos - i0;
    out[i] = pcm[i0] * (1 - frac) + pcm[i1] * frac;
  }
  return out;
}

function rms(pcm) {
  if (!pcm.length) return 0;
  let sum = 0;
  for (let i = 0; i < pcm.length; i += 1) sum += pcm[i] * pcm[i];
  return Math.sqrt(sum / pcm.length);
}

const modelPath = resolveSileroVadCppGgufPath({ bundleRoot });
if (!modelPath) {
  console.log(JSON.stringify({ available: false, reason: "no VAD model found", bundleRoot, wavPath }));
  process.exit(0);
}

const wav = readWavPcm16Mono(wavPath);
const pcm16k = resampleLinear(wav.pcm, wav.sampleRateHz, SR);
let detector;
try {
  detector = await createSileroVadDetector({
    sileroCppGgufPath: modelPath,
    sileroCppLibraryPath: libraryPath || undefined,
    bundleRoot,
    config: {
      sampleRate: SR,
      onsetThreshold: 0.5,
      pauseHangoverMs: 220,
      endHangoverMs: 500,
      minSpeechMs: 150,
    },
  });
} catch (err) {
  console.log(JSON.stringify({
    available: false,
    reason: "VAD provider unavailable",
    bundleRoot,
    wavPath,
    vadModelPath: modelPath,
    libraryPath,
    error: {
      name: err?.name ?? null,
      code: err?.code ?? null,
      message: err instanceof Error ? err.message : String(err),
    },
  }));
  process.exit(0);
}
const events = [];
const energyEvents = [];
detector.onVadEvent((e) => events.push(e));
detector.onEnergyEvent((e) => energyEvents.push(e));

const computeMs = [];
let ts = 0;
for (let i = 0; i < pcm16k.length; i += FRAME) {
  const frame = new Float32Array(FRAME);
  frame.set(pcm16k.subarray(i, Math.min(i + FRAME, pcm16k.length)));
  const t0 = performance.now();
  await detector.pushFrame({ pcm: frame, sampleRate: SR, timestampMs: ts });
  computeMs.push(performance.now() - t0);
  ts += (FRAME * 1000) / SR;
}
await detector.flush();

const starts = events.filter((e) => e.type === "speech-start");
const ends = events.filter((e) => e.type === "speech-end");
const pauses = events.filter((e) => e.type === "speech-pause");
const blips = events.filter((e) => e.type === "blip");
const median = (xs) => {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
};
const p95 = (xs) => {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(s.length * 0.95) - 1)];
};

console.log(JSON.stringify({
  available: true,
  bundleRoot,
  wavPath,
  vadModelPath: modelPath,
  wav: {
    sampleRateHz: wav.sampleRateHz,
    samples: wav.samples,
    audioSeconds: wav.samples / wav.sampleRateHz,
    rms: rms(wav.pcm),
  },
  resampled: {
    sampleRateHz: SR,
    samples: pcm16k.length,
    audioSeconds: pcm16k.length / SR,
    frameCount: Math.ceil(pcm16k.length / FRAME),
  },
  summary: {
    speechDetected: starts.length > 0,
    speechStarts: starts.length,
    speechEnds: ends.length,
    speechPauses: pauses.length,
    blips: blips.length,
    firstSpeechStartMs: starts[0]?.timestampMs ?? null,
    firstSpeechEndMs: ends[0]?.timestampMs ?? null,
    speechDurationMs: ends[0]?.speechDurationMs ?? null,
    energyEvents: energyEvents.length,
    computeMsMedian: median(computeMs),
    computeMsP95: p95(computeMs),
  },
  events,
  energyEvents,
}));
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const runnerRuntime = typescriptRunner(Boolean(args.lib));
  if (!runnerRuntime) {
    throw new Error("bun or node --import tsx is required to run plugin-local-inference VAD");
  }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "eliza-vad-wav-"));
  const runner = path.join(tmp, "run.mjs");
  fs.writeFileSync(runner, makeRunnerSource(args), "utf8");
  const child = spawnSync(runnerRuntime.cmd, [...runnerRuntime.args, runner], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    env: process.env,
    maxBuffer: 10 * 1024 * 1024,
  });
  let report;
  if (child.status !== 0) {
    report = {
      generatedAt: new Date().toISOString(),
      available: false,
      reason: "VAD WAV runner failed",
      exitCode: child.status,
      stdout: child.stdout,
      stderr: child.stderr,
    };
  } else {
    const lines = child.stdout.trim().split(/\r?\n/).filter(Boolean);
    report = JSON.parse(lines[lines.length - 1] ?? "{}");
    report.generatedAt = new Date().toISOString();
  }
  report.harness = path.relative(process.cwd(), __filename);
  fs.mkdirSync(path.dirname(args.report), { recursive: true });
  fs.writeFileSync(args.report, `${JSON.stringify(report, null, 2)}\n`);
  if (args.json) console.log(JSON.stringify(report, null, 2));
  else {
    console.log(`wrote ${args.report}`);
    console.log(
      `vad-from-wav: available=${report.available} speech=${report.summary?.speechDetected ?? false} firstStartMs=${report.summary?.firstSpeechStartMs ?? "n/a"}`,
    );
  }
}

main();
